### ISSUE TITLE
PSM not generating json

### ISSUE THREAD

**Issue by Phoust** [stopperw/pain-studio-mask#3]
I see the PSM client in the filters tab of OTD, but it doesn't seem to be generating the psm.json file. I also don't see the "PSM is loaded" in the console when I launch the app

**Comment by Phoust** [comment]
Thanks for the quick reply; Yes, after enabling the filter and interacting with the tablet, the logs do say that the json was written, ~~but it's not in any location I can find in the /OpenTabletDriver or any other system folders.~~

Wait, it seems it went straight to my home folder! I see it now. My mistake

[PSMClient:Info]	PSM Client v0.0.2 enabled!
[PSMConnection:Info]	Connection thread started.
[Gaomon M10K:Info]	Filters: PSM.OTD.PSMClient
[Settings:Info]	Driver is enabled.
[PSMClient:Info]	Default config for your tablet was written to psm.json
[PSMClient:Info]	Put it in target app's folder alongside PSM's wintab32.dll


The app I'm trying to run is [Verve Painter](https://www.taron.de/forum/viewtopic.php?f=4&t=4), which I confirmed uses the standard wintab api. In winecfg I've tried both Native Builtin and Native Windows for the wintab32. Here are those logs, which don't seem to help much!

wine Verve_painter.exe
0(8) : warning C7502: OpenGL does not allow type suffix 'f' on constant literals in versions below 120
0(55) : warning C7011: implicit cast from "int" to "float"
0(56) : warning C7011: implicit cast from "int" to "float"
0(57) : warning C7011: implicit cast from "int" to "float"
0(10) : warning C7011: implicit cast from "int" to "float"
0(48) : warning C7011: implicit cast from "int" to "float"
0(64) : warning C7011: implicit cast from "int" to "float"
0(76) : warning C7011: implicit cast from "int" to "float"
0(38) : warning C7011: implicit cast from "int" to "float"
0(56) : warning C7011: implicit cast from "int" to "float"
0(5) : warning C7011: implicit cast from "int" to "float"
0(20) : warning C7548: '&' requires "#extension GL_EXT_gpu_shader4 : enable" before use
0(27) : warning C7548: '&' requires "#extension GL_EXT_gpu_shader4 : enable" before use
0(20) : warning C7548: '&' requires "#extension GL_EXT_gpu_shader4 : enable" before use
0(27) : warning C7548: '&' requires "#extension GL_EXT_gpu_shader4 : enable" before use
0(29) : warning C7011: implicit cast from "int" to "float"
0(34) : warning C7011: implicit cast from "int" to "float"
0(39) : warning C7011: implicit cast from "int" to "float"
0(44) : warning C7011: implicit cast from "int" to "float"
0(49) : warning C7011: implicit cast from "int" to "float"
0(54) : warning C7011: implicit cast from "int" to "float"
0(63) : warning C7011: implicit cast from "int" to "float"
0(68) : warning C7011: implicit cast from "int" to "float"
0(13) : warning C7011: implicit cast from "int" to "float"
0(19) : warning C7011: implicit cast from "int" to "float"

**Comment by stopperw** [comment]
Fixed in [v0.1.0](https://github.com/stopperw/pain-studio-mask/pull/13) - want to make sure everything's good before the actual release, so the binaries are here: [PSM](https://github.com/stopperw/pain-studio-mask/actions/runs/25632101159), [PSM-OTD](https://github.com/stopperw/psm-otd/actions/runs/25631555310)

Verve Painter requires using the [wintab-proxy](https://github.com/stopperw/wintab-proxy) though.

**Comment by Phoust** [comment]
Thank you for the update! 
Hmm, I'm still not getting pressure sensitivity, but first want to confirm that I've set it up correctly (just to rule out user error);

- download the new PSM and wintab32i686 binaries from links you provided
- install PSM into OTD and set up the psm.json as normal
- place wintab32.dll next to the Verve executable and rename to wintab32_real.dll  
- download wintab-proxy and also place next to the Verve executable
- run with WINEDLLOVERRIDES="wintab32=n"

The app launches just fine and seems to correctly load wintab32, but here are the logs anyway in case there's anything useful:

`~/Applications/Verve$ wine Verve_painter.exe WINEDLLOVERRIDES="wintab32=n" -vv
0(8) : warning C7502: OpenGL does not allow type suffix 'f' on constant literals in versions below 120
0(55) : warning C7011: implicit cast from "int" to "float"
0(56) : warning C7011: implicit cast from "int" to "float"
0(57) : warning C7011: implicit cast from "int" to "float"
0(10) : warning C7011: implicit cast from "int" to "float"
0(48) : warning C7011: implicit cast from "int" to "float"
0(64) : warning C7011: implicit cast from "int" to "float"
0(76) : warning C7011: implicit cast from "int" to "float"
0(38) : warning C7011: implicit cast from "int" to "float"
0(56) : warning C7011: implicit cast from "int" to "float"
0(5) : warning C7011: implicit cast from "int" to "float"
0(20) : warning C7548: '&' requires "#extension GL_EXT_gpu_shader4 : enable" before use
0(27) : warning C7548: '&' requires "#extension GL_EXT_gpu_shader4 : enable" before use
0(20) : warning C7548: '&' requires "#extension GL_EXT_gpu_shader4 : enable" before use
0(27) : warning C7548: '&' requires "#extension GL_EXT_gpu_shader4 : enable" before use
0(29) : warning C7011: implicit cast from "int" to "float"
0(34) : warning C7011: implicit cast from "int" to "float"
0(39) : warning C7011: implicit cast from "int" to "float"
0(44) : warning C7011: implicit cast from "int" to "float"
0(49) : warning C7011: implicit cast from "int" to "float"
0(54) : warning C7011: implicit cast from "int" to "float"
0(63) : warning C7011: implicit cast from "int" to "float"
0(68) : warning C7011: implicit cast from "int" to "float"
0(13) : warning C7011: implicit cast from "int" to "float"
0(19) : warning C7011: implicit cast from "int" to "float"
[WTP] wintab32.DllMain(1ffe0000, 1, 00000000)
[*] PSM v0.1.0 is loaded!
[WTP] wintab32.DllMain: Forwarding DLL (wintab32) loaded (1ddc0000)
[E] WTInfo lp_output is null
[WTP] wintab32.DllMain(1ffe0000, 2, 00000000)
[*] PSM is now listening on 127.0.0.1:40302
[WTP] wintab32.DllMain(1ffe0000, 2, 00000000)
[*] Accepted connection from 127.0.0.1:35134
[*] Client: PSM-OTD 0.0.3
[*] 
 |     0: failed to fill whole buffer
 |  
 |  Location:
 |     wintab32/src/lib.rs:147
 |  
 |  Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
 |  Run with RUST_BACKTRACE=full to include source snippets.
[*] Connection from 127.0.0.1:35134 ended
[*] PSM is now listening on 127.0.0.1:40302
[*] Accepted connection from 127.0.0.1:43166
[*] Client: PSM-OTD 0.0.3
[*] 
 |     0: failed to fill whole buffer
 |  
 |  Location:
 |     wintab32/src/lib.rs:147
 |  
 |  Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
 |  Run with RUST_BACKTRACE=full to include source snippets.
[*] Connection from 127.0.0.1:43166 ended
[*] PSM is now listening on 127.0.0.1:40302
[*] Accepted connection from 127.0.0.1:34808
[*] Client: PSM-OTD 0.0.3
[*] 
 |     0: failed to fill whole buffer
 |  
 |  Location:
 |     wintab32/src/lib.rs:147
 |  
 |  Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
 |  Run with RUST_BACKTRACE=full to include source snippets.
[*] Connection from 127.0.0.1:34808 ended
[*] PSM is now listening on 127.0.0.1:40302
[WTP] wintab32.DllMain(1ffe0000, 0, 00000001)
[WTP] wintab32.DllMain: Forwarding DLL (wintab32) freed
`

**Comment by stopperw** [comment]
> [*] Client: PSM-OTD 0.0.3

You didn't update the OpenTabletDriver plugin to the correct version: [get it from here, down in the artifacts](https://github.com/stopperw/psm-otd/actions/runs/25631555310)

Disable "Send movement packets only in proximity" if pressure doesn't work after connection.

**Comment by Phoust** [comment]
Hmm, that's the version I downloaded. I only see one item in the Artifacts section, is there some other place I should be looking? Apologies if I'm missing something obvious!

**Comment by stopperw** [comment]
The file there is correct...

Did you restart OpenTabletDriver afterwards? Also, you can try just downloading and installing the plugin again.

**Comment by Phoust** [comment]
Tried it again. This time I uninstalled by manually deleting the folder and reinstalling from the menu and... It's working now! My beloved Verve, on Linux now, haha.

You're a hero, thanks so much. If you have a ko-fi or something, I'd love to kick you a few bucks for your time

**Comment by stopperw** [comment]
You are welcome! I do have a [Ko-fi page](https://ko-fi.com/spikycube), donate at your own discretion of course.

---

[Pain Studio Mask v0.1.0](https://github.com/stopperw/pain-studio-mask/releases/tag/v0.1.0) released and that should have fixed this issue! If something is still wrong, please reopen this issue or open a new one.
